[package]
name = "oxynium"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.0.26", features = ["derive"] }
rand= "0.8.5"
regex = "1"
phf = { version = "0.11", features = ["macros"] }