#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

cargo run "$@"

nasm -f elf64 out.asm

ld -s -o out out.o

#rm out.o
#rm out.asm

# shellcheck disable=SC2059
printf "${GREEN}Program output:${NC}\n"

./out
