# binop_separator = "Front"
# condense_wildcard_suffixes = true
# enum_discrim_align_threshold = 30
# fn_single_line = true
# force_explicit_abi = true
# format_macro_matchers = true
# format_strings = true
# hex_literal_case = "Upper"
# hide_parse_errors = true
# imports_granularity = "Module"
# group_imports = "StdExternalCrate"
# reorder_impl_items = true
reorder_imports = true
reorder_modules = true
use_try_shorthand = true
# wrap_comments = true
