describe 'Boolean And'

expect 'true && true' '1'
expect 'true && false' '0'
expect 'false && true' '0'
expect 'false && false' '0'
expect 'true && true && true' '1'
expect 'true && true && false' '0'
expect 'true && false && true' '0'
expect 'true && false && false' '0'
expect 'false && true && true' '0'
expect 'false && true && false' '0'
expect 'false && false && true' '0'
expect 'false && false && false' '0'
expect 'true && true && true && true' '1'


describe 'Boolean Or'

expect 'true || true' '1'
expect 'true || false' '1'
expect 'false || true' '1'
expect 'false || false' '0'
expect 'true || true || true' '1'
expect 'true || true || false' '1'
expect 'true || false || true' '1'
expect 'true || false || false' '1'
expect 'false || true || true' '1'
expect 'false || true || false' '1'
expect 'false || false || true' '1'
expect 'false || false || false' '0'
expect 'true || true || true || true' '1'


describe 'Boolean Not'

expect '!true' '0'
expect '!false' '1'
expect '!!true' '1'
expect '!!false' '0'
expect '!(true && true)' '0'
expect '!(true && false)' '1'
expect '!(false && true)' '1'