describe 'Edge Cases'

expect '' ''
expect '' ' '
expect '' '


 '

expect_err 'SyntaxError' ';'
expect_err 'SyntaxError' ';;'
expect '' ';1'
expect '' ';1;'
expect '' ';;;;1;;;;;'
expect '' '1;;;;;;'
expect '' '1;'
expect '' '1'

# weird EOF cases
expect_err 'UnknownSymbolError' 'mut'
expect_err 'SyntaxError' 'const'
expect_err 'SyntaxError' 'let'
expect_err 'SyntaxError' 'let mut'
expect_err 'SyntaxError' 'fn'
expect_err 'SyntaxError' 'extern'
expect_err 'SyntaxError' 'extern fn'
expect_err 'SyntaxError' 'extern const a'
expect_err 'SyntaxError' 'extern const a:'
expect_err 'SyntaxError' 'extern const a: Str = '
expect_err 'SyntaxError' 'const a: Str = '
expect_err 'SyntaxError' 'fn a'
expect_err 'SyntaxError' 'fn a('
expect_err 'SyntaxError' 'fn a(a'
expect_err 'SyntaxError' 'fn a(a: '
expect_err 'SyntaxError' 'fn a(a: Str'
expect_err 'SyntaxError' 'fn a(a: Str) {'
expect_err 'SyntaxError' 'fn a(a: Str) { 1;'
expect_err 'SyntaxError' 'for'
expect_err 'SyntaxError' 'for {'
expect_err 'SyntaxError' 'for { 1;'
expect_err 'SyntaxError' 'if'
expect_err 'SyntaxError' 'if {'
expect_err 'SyntaxError' 'if true'
expect_err 'SyntaxError' 'if true {'
expect_err 'SyntaxError' 'if true { 1;'
expect_err 'SyntaxError' 'class'
expect '' 'class S'
expect_err 'SyntaxError' 'class S {'
expect_err 'SyntaxError' 'class S { x'
expect_err 'SyntaxError' 'class S { x:'
expect_err 'SyntaxError' 'class S { x: Str'
expect_err 'SyntaxError' 'new '
expect_err 'UnknownSymbolError' 'new S'
expect_err 'SyntaxError' 'new S { '
expect_err 'SyntaxError' 'new S { a'
expect_err 'SyntaxError' 'new S { a:'
expect_err 'SyntaxError' 'new S { a: 1'
