describe 'Integer GT'

expect_expr_bool '1 > 2' 'false'
expect_expr_bool '2 > 1' 'true'
expect_expr_bool '1 > 1' 'false'
expect_expr_bool '1 > 0' 'true'
expect_expr_bool '0 > 1' 'false'
expect_expr_bool '1 > -1' 'true'
expect_expr_bool '-1 > 1' 'false'
expect_expr_bool '1 + 4 > 2' 'true'
expect_expr_bool '1 + 4 > 2 * 3' 'false'
expect_err 'true > 2' 'TypeError'
expect_err '1 > 2 > 4' 'TypeError'
expect_err '2 > ""' 'TypeError'
expect_err '"" > ""' 'TypeError'
expect_err '"" > true' 'TypeError'
expect_err '2 > false' 'TypeError'
expect_err '"" > 2' 'TypeError'
expect_err 'fn a(); a > 4' 'TypeError'


describe 'Integer LT'

expect_expr_bool '1 < 2' 'true'
expect_expr_bool '2 < 1' 'false'
expect_expr_bool '1 < 1' 'false'
expect_expr_bool '1 < 0' 'false'
expect_expr_bool '0 < 1' 'true'
expect_expr_bool '1 < -1' 'false'
expect_expr_bool '-1 < 1' 'true'
expect_expr_bool '1 + 4 < 2' 'false'
expect_expr_bool '1 + 4 < 2 * 3' 'true'
expect_err 'true < 2' 'TypeError'
expect_err '1 < 2 < 4' 'TypeError'
expect_err '2 < ""' 'TypeError'
expect_err '"" < ""' 'TypeError'
expect_err '"" < true' 'TypeError'
expect_err '2 < false' 'TypeError'
expect_err '"" < 2' 'TypeError'
expect_err 'fn a(); a < 4' 'TypeError'


describe 'Integer GE'

expect_expr_bool '1 >= 2' 'false'
expect_expr_bool '2 >= 1' 'true'
expect_expr_bool '1 >= 1' 'true'
expect_expr_bool '1 >= 0' 'true'
expect_expr_bool '0 >= 1' 'false'
expect_expr_bool '1 >= -1' 'true'
expect_expr_bool '-1 >= 1' 'false'
expect_expr_bool '1 + 4 >= 2' 'true'
expect_expr_bool '1 + 4 >= 2 * 3' 'false'
expect_err 'true >= 2' 'TypeError'
expect_err '1 >= 2 >= 4' 'TypeError'
expect_err '2 >= ""' 'TypeError'
expect_err '"" >= ""' 'TypeError'
expect_err '"" >= true' 'TypeError'
expect_err '2 >= false' 'TypeError'
expect_err '"" >= 2' 'TypeError'
expect_err 'fn a(); a >= 4' 'TypeError'


describe 'Integer LE'

expect_expr_bool '1 <= 2' 'true'
expect_expr_bool '2 <= 1' 'false'
expect_expr_bool '1 <= 1' 'true'
expect_expr_bool '1 <= 0' 'false'
expect_expr_bool '0 <= 1' 'true'
expect_expr_bool '1 <= -1' 'false'
expect_expr_bool '-1 <= 1' 'true'
expect_expr_bool '1 + 4 <= 2' 'false'
expect_expr_bool '1 + 4 <= 2 * 3' 'true'
expect_err 'true <= 2' 'TypeError'
expect_err '1 <= 2 <= 4' 'TypeError'
expect_err '2 <= ""' 'TypeError'
expect_err '"" <= ""' 'TypeError'
expect_err '"" <= true' 'TypeError'
expect_err '2 <= false' 'TypeError'
expect_err '"" <= 2' 'TypeError'
expect_err 'fn a(); a <= 4' 'TypeError'


describe 'Integer EQ'

expect_expr_bool '1 == 2' 'false'
expect_expr_bool '2 == 1' 'false'
expect_expr_bool '1 == 1' 'true'
expect_expr_bool '1 == 0' 'false'
expect_expr_bool '0 == 1' 'false'
expect_expr_bool '1 == -1' 'false'
expect_expr_bool '-1 == 1' 'false'
expect_expr_bool '1 + 4 == 2' 'false'
expect_expr_bool '1 + 4 == 2 * 3' 'false'
expect_err 'true == 2' 'TypeError'
expect_err '1 == 2 == 4' 'TypeError'
expect_err '2 == ""' 'TypeError'
expect_err '"" == ""' 'TypeError'
expect_err '"" == true' 'TypeError'
expect_err '2 == false' 'TypeError'
expect_err 'false == false' 'TypeError'
expect_err '"" == 2' 'TypeError'
expect_err 'fn a(); a == 4' 'TypeError'


describe 'Integer NE'

expect_expr_bool '1 != 2' 'true'
expect_expr_bool '2 != 1' 'true'
expect_expr_bool '1 != 1' 'false'
expect_expr_bool '1 != 0' 'true'
expect_expr_bool '0 != 1' 'true'
expect_expr_bool '1 != -1' 'true'
expect_expr_bool '-1 != 1' 'true'
expect_expr_bool '1 + 4 != 2' 'true'
expect_expr_bool '1 + 4 != 2 * 3' 'true'
expect_err 'true != 2' 'TypeError'
expect_err '1 != 2 != 4' 'TypeError'
expect_err '2 != ""' 'TypeError'
expect_err '"" != ""' 'TypeError'
expect_err '"" != true' 'TypeError'
expect_err '2 != false' 'TypeError'
expect_err 'false != false' 'TypeError'
expect_err '"" != 2' 'TypeError'
expect_err 'fn a(); a != 4' 'TypeError'