name: Tests

on:
  push:
    branches: [ "master", "stable" ]
  pull_request:
    branches: [ "master", "stable" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Macos E2E
    runs-on: macos-latest-xl
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: sudo port install nasm
    - name: Run tests
      run: bin/test
